### PR TITLE
MLIBZ-1951: crashing with empty body error

### PR DESCRIPTION
**Pull request by heyzooi**
#### Description

Crash was happening when a DLC/BL is returning an empty body error

#### Changes

* Avoiding force unwrap optionals when building error objects

#### Tests

* No need for additional unit test

### CODE REVIEW

**Comment by ivanstoyanov** [comment]
"The diff coverage is 100%" - how does that work, if the commit has no tests?

**Comment by heyzooi** [comment]
@ivanstoyanov our current tests are already covering this part of the code. we were forcing an unwrap of a value before (which could cause a crash). the unwrap is now removed which will not crash anymore.

**Comment by tejasranade** [comment]
I did not see Ivan's comment before my review :) We're asking slightly different things, I think.
IMO it's useful to add a test that mocks the kind of response that resulted in this bug.

**Comment by heyzooi** [comment]
@tejasranade right... doing it now

**Comment by heyzooi** [comment]
@tejasranade unit test is now added. let me know if I can merge now

**Pull request merged**
